---
title: "Publications"
---

[Google scholar](https://scholar.google.com/citations?user=rFr2Xx4AAAAJ&hl=en&oi=ao)

# In-preparation

[Kauffman, Kayla M.]{style="color:purple;"}, Georgia Titcomb, Mark Janko, Randriamoria Toky Maheriniaina, Michelle Pender, Voahangy Soarimalala, Peter Mucha, Hillary Young, Charles Nunn. Multihost parasite sharing between primary and secondary host species across a suite of parasites occurs near forest boundaries and where many infected primary hosts are found.

Georgia Titcomb, [Kayla Kauffman]{style="color:purple;"}, Tyler Barrett, Charles L. Nunn. Movement and sociodemographic predictors of zoonotic and human hookworm infection.

[Kauffman, Kayla M.]{style="color:purple;"} and Rajaonarivelo, Jeanne Arline and Rabeson, Sitraka and Rakotondramanana, Rijaniaina Tsiry and Maheriniaina, Randriamoria Toky and Randria, Rianja and Pender, Michelle and Soarimalala, Voahangy and Nunn, Charles L. and Tortosa, Pablo and Young, Hillary, Assessing the Cross-Species Effects of Dog *Leptospira* Vaccinations in Rural Northeastern Madagascar.

# Published works

If you have trouble accessing any of these articles please email me and I will send you a pdf.

## 2026

[Kauffman, Kayla M.]{style="color:purple;"}, Michelle Pender; Jean Yves Rabezara; Prisca Rahary; Mark Janko; Tyler Barrett; Lev Kolinski; Maheriniaina Toky Randriamoria; Voahangy Soarimalala; James Moody; David Lopez-Carr; Randall Kramer; Georgia Titcomb; Charles Nunn. Sociodemographic characteristics predict land use patterns by farmers near a protected area in Madagascar. Scientific Reports. 2026. <https://doi.org/10.1038/s41598-026-40592-6>

Camille M. DeSisto\*; Raquel A. Binder\*; [Kayla Kauffman]{style="color:purple;"}; Tyler Barrett; Michelle Pender; Randall Kramer; Voahangy Soarimalala; James Moody; Charles L. Nunn. Predictors of Centrality on Real World Human Transmission Networks in Rural Madagascar. PLoS Glob Public Health. 2026 6(1): e0005661. <https://doi.org/10.1371/journal.pgph.0005661>

Jeanne A. Rajaonarivelo\*, [Kayla M. Kauffman\*]{style="color:purple;"}, Toky M. Randriamoria, James P. Herrera, Natalie Wickenkamp, Magali Turpin, Fiona Baudino, Hillary S. Young, Voahangy Soarimalala, Steven M. Goodman, Charles L. Nunn, Pablo Tortosa. Leptospira prevalence and lineages vary across land-use types due to shifts in small mammal communities. Applied Environmental Microbiology. 2026. e02061-25. <http://doi.org/10.1128/aem.02061-25>

- AEM commentary: Changing landscapes, shifting reservoirs: land-use change and Leptospira ecology in Madagascar. <https://doi.org/10.1128/aem.00487-26>
- [Poster presented at Stanford Global Health Convening 2026](posts/2026-01-28-smlepto-poster/index.qmd)

## 2025

Solis A, Anaeme A, Titcomb G, Janko M, Rabezara JY, Barrett TM, [Kauffman, K]{style="color:purple;"}, Pender M, Soarimalala V, Kolinski L, Kramer R, Young H, Nunn CL. One Health Disparities and Blastocystis infection among smallholder farmers in northeastern Madagascar. PLOS Glob Public Health. 2025 Oct 13;5(10):e0005189. <https://doi.org/10.1371/journal.pgph.0005189>

Dubrulle J\*, [Kauffman, K\*]{style="color:purple;"}, Soarimalala V, Randriamoria T, Goodman SM, Herrera J, Nunn C, Tortosa P. Effects of habitat degradation on Hantavirus infection among introduced and endemic small mammals of Madagascar. Ecology and Evolution. 2025. <https://doi.org/10.1002/ece3.70914> \* *co-first authors*

-   Press releases: <https://news.ucsb.edu/2025/021825/hantavirus-madagascar-linked-black-rats-agricultural-areas> and <https://researchblog.duke.edu/2025/04/08/forests-and-disease-risk-hantavirus-in-madagascar/>
- [Poster presented at EEID 2025](posts/2025-06-16-hookworm-poster/index.qmd)

## 2024

Tyler Barrett, Georgia Titcomb, Mark Janko, Michelle Pender, [Kayla Kauffman]{style="color:purple;"}, Alma Solis, Toky Randriamoria, Hillary Young, Peter Mucha, James Moody, Randall Kramer, Voahangy Soarimalala, and Charles Nunn. Disentangling Social, Environmental, and Zoonotic Transmission Pathways of a Gastrointestinal Protozoan (Blastocystis spp.) in Northeast Madagascar. American Journal of Biological Anthropology. 2024. <https://pubmed.ncbi.nlm.nih.gov/39287986/>

Carcauzon V, Herrera JP, [Kauffman KM]{style="color:purple;"}, Baudino F, Wickenkamp N, Randriamoria TM, Soarimalala V, Goodman SM, Nunn SM, Lebarbenchon C, and Tortosa P. Astroviruses in terrestrial Malagasy mammals. PLOS Neglected Tropical Diseases. 2024. <https://doi.org/10.1371/journal.pntd.0012263>

## 2023

MV Evans, T Ramiadantsoa, [K Kauffman]{style="color:purple;"}, J Moody, C Nunn, JY Rabezara, P Raharimalala, TM Randriamoria, V Soarimalala, G Titcomb, A Garchitorena, and B Roche. Socio-demographic variables can guide prioritized testing strategies for epidemic control in resource-limited contexts. Journal of Infectious Diseases. 2023. <https://doi.org/10.1093/infdis/jiad076>

## 2022

[Kauffman, Kayla]{style="color:purple;"}, Werner Courtney S., Titcomb Georgia, Pender Michelle, Rabezara Jean Yves, Herrera James P., Shapiro Julie Teresa, Solis Alma, Soarimalala Voahangy, Tortosa Pablo, Kramer Randall, Moody James, Mucha Peter J. and Nunn Charles. 2022. Comparing transmission potential networks based on social network surveys, close contacts and environmental overlap in rural Madagascar. J. R. Soc. Interface. 19:20210690. 20210690. <http://doi.org/10.1098/rsif.2021.0690>

## 2021

[Kauffman, Kayla M.]{style="color:purple;"}, Todd E. Cornish, Kevin Monteith, Brant A. Schumaker, Tayler LaSharr, Katey Huggler, and Myrna Miller. Detection of Deer atadenovirus A DNA in dam and offspring pairs of Rocky Mountain mule deer (Odocoileus hemionus hemionus) and Rocky Mountain elk (Cervus canadensis nelson). Journal of Wildlife Diseases, 57(2), 2021. <https://doi.org/10.7589/JWD-D-20-00034>

## 2019

[Kauffman, Kayla M.]{style="color:purple;"}. Expanding the knowledge of the epidemiology of Adenovirus Hemorrhagic Disease: Deer atadenovirus A genotype distribution in Western North America and dam to offspring transmission (Master's Thesis). University of Wyoming. Presented 7 July 2019. Published 16 Aug 2019. Proquest (22620093).

## 2018

White M, [Kauffman, K]{style="color:purple;"}, Lewis J, Miller R. 2018. Wild pigs breach farm fence through harvest time in southern San Joaquin Valley. Calif Agr 72(2):120-126. <https://doi.org/10.3733/ca.2018a0017>
